export const Texts = {
    genericError: "genericError",
    welcomeMessage: "welcomeMessage",
    loginWithGoogle: "loginWithGoogle",
    loginWithEmail: "loginWithEmail",
    signup: "signup",
    signout: "signout",
    login: "login",
    forgotPassword: "forgotPassword",
    email: "email",
    password: "password",
    confirmPassword: "confirmPassword",
    loginInstead: "loginInstead",
    success: "success",
    yes: "yes",
    no: "no",
    ok: "ok",
    cancel: "cancel",
    back: "back",
    confirm: "confirm",
    proceed: "proceed",
    goBack: "goBack",
    heyCurious: "heyCurious",
    pageUnderConstruction: "pageUnderConstruction",
    exploreApp: "exploreApp",
    displayName: "displayName",
    sendLink: "sendLink",
    changeTheme: "changeTheme",
    helloName: "helloName",
    accountCreated: "accountCreated",
    verifyEmail: "verifyEmail",
    resendVerificationEmail: "resendVerificationEmail",
    resendSuccessfulMessage: "resendSuccessfulMessage",
    welcomeToApp: "welcomeToApp",
    noteFromDeveloper: "noteFromDeveloper",
    appExplanation: "appExplanation",
    linkedinProfile: "linkedinProfile",
    profileSettings: "profileSettings",
    editName: "editName",
    changePassword: "changePassword",
    deleteAccount: "deleteAccount",
    sure: "sure",
    sureToDeleteAccount: "sureToDeleteAccount",
    passwordConfirmMessage: "passwordConfirmMessage",
    errorMessages: {
        tooManyRequestsResend: "tooManyRequestsResend",
        fillAllFields: "fillAllFields",
        enterValidEmail: "enterValidEmail",
        passwordsDontMatch: "passwordsDontMatch",
        emailAddressAlreadyInUse: "emailAddressAlreadyInUse",
        invalidEmail: "invalidEmail",
        weakPassword: "weakPassword",
        userNotFound: "userNotFound",
        wrongPassword: "wrongPassword"
    },
    screenTitles: {
        titleSignup: "titleSignup",
        titleLogin: "titleLogin",
        titleProfile: "titleProfile"
    }
 }

 export const LocaleTypes = {
     english: "en",
     turkish: "tr",
     device: "device",
 }